# Configure Dependabot scanning.
version: 2

updates:
  # Check for updates to GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
  # Update some npm dependencies in groups.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 40
    allow:
      - dependency-name: "backbone"
      - dependency-name: "clipboard"
      - dependency-name: "element-closest"
      - dependency-name: "formdata-polyfill"
      - dependency-name: "json2php"
    ignore:
      - dependency-name: "@wordpress/*"
    groups:
      css-sass:
        patterns:
          - "autoprefixer"
          # postcss and css related dependencies.
          - "*css*"
          - "*sass"
      qunit:
        patterns:
          - "*qunit*"
          - "sinon*"
      # Webpack build process related dependencies.
      webpack:
        patterns:
          - "*webpack*"
          - "source-map-loader"
      # Officially maintained GruntJS dependencies.
      grunt-contrib:
        patterns:
          - "grunt-contrib-*"
      # All other GruntJS related dependencies.
      grunt:
        patterns:
          - "*grunt*"
      docker-related:
        patterns:
          - "dotenv*"
          - "wait-on"
      miscellaneous:
        patterns:
          - "chalk"
          - "check-node-version"
          - "ink-docstrap"
          - "install-changed"
          - "uuid"
      uglify:
        patterns:
          - "*uglify*"
