# Configure Dependabot scanning.
version: 2

updates:
  # Check for updates to GitHub Actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
  # Update some npm dependencies in groups.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    ignore:
      - dependency-name: "@wordpress/*"
    groups:
      css-sass:
        patterns:
          - "autoprefixer"
          # postcss and css related dependencies.
          - "*css*"
          - "*sass"
      qunit:
        patterns:
          - "*qunit*"
          - "sinon*"
      # Webpack build process related dependencies.
      webpack:
        patterns:
          - "*webpack*"
          - "react-refresh"
          - "source-map-loader"
      # Officially maintained GruntJS dependencies.
      dev-grunt-contrib:
        patterns:
          - "grunt-contrib-*"
      # All other GruntJS related dependencies.
      dev-grunt:
        patterns:
          - "*grunt*"
      dev-docker:
        patterns:
          - "dotenv*"
          - "wait-on"
      dev-miscellaneous:
        patterns:
          - "chalk"
          - "check-node-version"
          - "ink-docstrap"
          - "install-changed"
          - "matchdep"
          - "uuid"
      dev-uglify:
        patterns:
          - "*uglify*"
      # Update some external library dependencies.
      external-jquery:
        patterns:
          - "jquery*"
      external-react:
        patterns:
          - "react*"
          - "!react-refresh"
      external-polyfills:
        patterns:
          - "core-js-url-browser"
          - "element-closest"
          - "formdata-polyfill"
          - "imagesloaded"
          - "objectFitPolyfill"
          - "polyfill-library"
          - "regenerator-runtime"
          - "whatwg-fetch"
      external-masonry:
        patterns:
          - "masonry-layout"
      external-miscellaneous:
        patterns:
          - "backbone"
          - "clipboard"
          - "hoverintent"
          - "lodash"
          - "moment"
          - "underscore"
