name: Cleanup Pull Requests

on:
  push:
    branches:
      - trunk
      - '3.[89]'
      - '[4-9].[0-9]'
      - test-close-prs
  schedule:
    - cron: '0 */12 * * *'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  # Runs the QUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Checks out the repository.
  close-prs-push:
    name: Close pull requests on commit
    runs-on: ubuntu-latest
#    if: ${{ github.repository == 'WordPress/wordpress-develop' && github.event_name == 'push' }}

    steps:
      - name: Extract ticket numbers
        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667 # v5.0.0
        with:
          script: |
            const fixesReg = new RegExp( 'Fixes(.*)\.','g' );
            const numbersReg = new RegExp( '[0-9]+', 'g' );
            const fixesLine = fixesReg.exec( "${{ github.event.head_commit.message }}" );
            const ticketList = numbersReg.exec( fixesLine );

            console.log( fixesLine );
            console.log( ticketList );
