name: PHPUnit Tests

on:
  push:
    branches:
      - master
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
    tags:
      - '3.[7-9]*'
      - '[4-9].[0-9]*'
  pull_request:
    branches:
      - master
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
  workflow_dispatch:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

env:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${{ true }}
  COMPOSER_INSTALL: ${{ false }}
  # Controls which NPM script to use for running PHPUnit tests. Options ar `php` and `php-composer`.
  PHPUNIT_SCRIPT: php
  LOCAL_PHP_MEMCACHED: ${{ false }}
  SLOW_TESTS: 'external-http,media,restapi'

jobs:
  # Sets up the workflow for testing.
  #
  # Performs the following steps:
  # - Cancels all previous workflow runs for pull requests that have not completed.
  setup-workflow:
    name: Setup Workflow
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}

    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@3d86a7cc43670094ac248017207be0295edbc31d # v0.8.0

  # Runs the PHPUnit tests for WordPress.
  #
  # Performs the following steps:
  # - Set environment variables.
  # - Sets up the environment variables needed for testing with memcached (if desired).
  # - Installs NodeJS 14.
  # - Sets up caching for NPM.
  # - Installs NPM dependencies
  # - Configures caching for Composer.
  # - Installs Composer dependencies (if desired).
  # - Logs Docker debug information (about both the Docker installation within the runner).
  # - Starts the WordPress Docker container.
  # - Starts the memcached server after the Docker network has been created (if desired).
  # - Logs WordPress Docker container debug information.
  # - Logs debug general information.
  # - Logs the running Docker containers.
  # - Logs debug information about what's installed within the WordPress Docker containers.
  # - Install WordPress within the Docker container.
  # - Run the PHPUnit tests.
  # - Checks out the WordPress Test reporter repository.
  # - Reconnect the directory to the Git repository.
  # - Submit the test results to the WordPress.org host test results.
  # - todo: Configure Slack notifications for failing tests.
  test-php:
    name: ${{ matrix.php }}${{ matrix.multisite && ' multisite' || '' }}${{ matrix.split_slow && ' slow tests' || '' }} ${{ matrix.memcached && ' with memcached' || '' }} on ${{ matrix.os }}
    needs: setup-workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [ '7.3' ]
        phpunit: [ '7.3' ]
        os: [ ubuntu-latest ]
        memcached: [ false ]
        split_slow: [ false ]
        multisite: [ false, true ]
        include:
          # Additional "slow jobs for PHP < 7.0
          - php: '5.6'
            phpunit: '4-php-5.6'
            os: ubuntu-latest
            memcached: false
            multisite: false
            split_slow: true
          - php: '5.6'
            phpunit: '4-php-5.6'
            os: ubuntu-latest
            memcached: false
            multisite: true
            split_slow: true
          - php: '5.5'
            phpunit: '5.5'
            os: ubuntu-latest
            memcached: false
            multisite: false
            split_slow: true
          - php: '5.5'
            phpunit: '5.5'
            os: ubuntu-latest
            memcached: false
            multisite: true
            split_slow: true
          - php: '5.4'
            phpunit: '5.4'
            os: ubuntu-latest
            memcached: false
            multisite: false
            split_slow: true
          - php: '5.4'
            phpunit: '5.4'
            os: ubuntu-latest
            memcached: false
            multisite: true
            split_slow: true
          - php: '5.3'
            phpunit: '5.3'
            os: ubuntu-latest
            memcached: false
            multisite: false
            split_slow: true
          - php: '5.3'
            phpunit: '5.3'
            os: ubuntu-latest
            memcached: false
            multisite: true
            split_slow: true

          # Additional test jobs.
          - php: '7.2'
            phpunit: '7.2'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '7.2'
            phpunit: '7.2'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '7.1'
            phpunit: '7.1'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '7.1'
            phpunit: '7.1'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '7.0'
            phpunit: '6-php-7.0'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '7.0'
            phpunit: '6-php-7.0'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '5.6'
            phpunit: '4-php-5.6'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '5.6'
            phpunit: '4-php-5.6'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '5.5'
            phpunit: '5.5'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '5.5'
            phpunit: '5.5'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '5.4'
            phpunit: '5.4'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '5.4'
            phpunit: '5.4'
            os: ubuntu-latest
            memcached: false
            multisite: true
          - php: '5.3'
            phpunit: '5.3'
            os: ubuntu-latest
            memcached: false
            multisite: false
          - php: '5.3'
            phpunit: '5.3'
            os: ubuntu-latest
            memcached: false
            multisite: true
          # Include job for PHP 7.3 with memcached.
          - php: '7.3'
            phpunit: '7.3'
            os: ubuntu-latest
            memcached: true
            multisite: false
          - php: '7.3'
            phpunit: '7.3'
            os: ubuntu-latest
            memcached: true
            multisite: true
    env:
      LOCAL_PHP: ${{ matrix.php }}-fpm
      LOCAL_PHPUNIT: ${{ matrix.phpunit }}-fpm
      LOCAL_PHP_MEMCACHED: ${{ matrix.memcached }}
      PHPUNIT_CONFIG: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}

    steps:
      - name: Configure environment variables
        run: |
          echo "PHP_FPM_UID=$(id -u)" >> $GITHUB_ENV
          echo "PHP_FPM_GID=$(id -g)" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Install NodeJS
        uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea # v2.1.5
        with:
          node-version: 14

      - name: Use cached Node modules
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Get composer cache directory
        id: composer-cache
        if: ${{ env.COMPOSER_INSTALL == true }}
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer dependencies
        if: ${{ env.COMPOSER_INSTALL == true }}
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6 # v2.1.4
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        if: ${{ env.COMPOSER_INSTALL == true }}
        run: |
          docker-compose run --rm php composer --version
          docker-compose run --rm php composer install

      - name: Docker debug information
        run: |
          docker -v
          docker-compose -v

      - name: Start Docker environment
        run: |
          npm run env:start

      # The memcached server needs to start after the Docker network has been set up with `npm run env:start`.
      - name: Start the Memcached server.
        if: ${{ matrix.memcached }}
        run: |
          cp tests/phpunit/includes/object-cache.php src/wp-content/object-cache.php
          docker run --name memcached --net $(basename "$PWD")_wpdevnet -d memcached

      - name: General debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version
          svn --version

      - name: Log running Docker containers
        run: docker ps -a

      - name: WordPress Docker container debug information
        run: |
          docker-compose run --rm mysql mysql --version
          docker-compose run --rm php php --version
          docker-compose run --rm php php -m
          docker-compose run --rm php php -i
          docker-compose run --rm php locale -a

      - name: Install WordPress
        run: npm run env:install

      - name: Run slow PHPUnit tests
        if: ${{ matrix.split_slow }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c ${{ env.PHPUNIT_CONFIG }} --group ${{ env.SLOW_TESTS }}

      - name: Run PHPUnit tests for single site excluding slow tests
        if: ${{ matrix.php < '7.0' && ! matrix.split_slow && ! matrix.multisite }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c ${{ env.PHPUNIT_CONFIG }} --exclude-group ${{ env.SLOW_TESTS }},ajax,ms-files,ms-required

      - name: Run PHPUnit tests for Multisite excluding slow tests
        if: ${{ matrix.php < '7.0' && ! matrix.split_slow && matrix.multisite }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c ${{ env.PHPUNIT_CONFIG }} --exclude-group ${{ env.SLOW_TESTS }},ajax,ms-files,ms-excluded,oembed-headers

      - name: Run PHPUnit tests
        if: ${{ matrix.php >= '7.0' }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c ${{ env.PHPUNIT_CONFIG }}

      - name: Run AJAX tests
        if: ${{ ! matrix.split_slow && ! matrix.multisite }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c ${{ env.PHPUNIT_CONFIG }} --group ajax

      - name: Run tests as a multisite install
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c tests/phpunit/multisite.xml

      - name: Run ms-files tests as a multisite install
        if: ${{ matrix.multisite && ! matrix.split_slow }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c tests/phpunit/multisite.xml --group ms-files

      - name: Run external HTTP tests
        if: ${{ ! matrix.multisite && ! matrix.split_slow }}
        run: npm run test:${{ env.PHPUNIT_SCRIPT }} -- --verbose -c phpunit.xml.dist --group external-http

      - name: Checkout the WordPress Test Reporter
        if: ${{ github.repository == 'WordPress/wordpress-develop' && github.ref == 'refs/heads/master' && matrix.report }}
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          repository: 'WordPress/phpunit-test-runner'
          path: 'test-runner'

      - name: Submit test results to the WordPress.org host test results
        if: ${{ github.repository == 'WordPress/wordpress-develop' && github.ref == 'refs/heads/master' && matrix.report }}
        env:
          WPT_REPORT_API_KEY: "${{ secrets.WPT_REPORT_API_KEY }}"
        run: docker-compose run --rm -e WPT_REPORT_API_KEY -e WPT_PREPARE_DIR=/var/www -e WPT_TEST_DIR=/var/www php php test-runner/report.php
