name: Props Bot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created
      - deleted

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  # Runs PHP coding standards checks.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Configures caching for PHPCS scans.
  # - Installs Composer dependencies.
  # - Make Composer packages available globally.
  # - Runs PHPCS on the full codebase with warnings suppressed.
  # - Generate a report for displaying issues as pull request annotations.
  # - Runs PHPCS on the `tests` directory without warnings suppressed.
  # - Generate a report for displaying `test` directory issues as pull request annotations.
  # - Ensures version-controlled files are not modified or deleted.
  props-bot:
    name: Generate a list of props
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    timeout-minutes: 20
    if: ${{ contains( fromJSON( '["pull_request_review", "pull_request_review_comment"]' ), github.event_name ) || github.event.action != 'labeled' || 'props-bot' != github.event.action.label.name }}

    steps:
      - name: Fetch props
        uses: WordPress/props-bot-action@update/comment-format

      - name: Remove props-bot label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: ${{ github.event.action == 'labeled' && 'props-bot' == github.event.action.label.name }}
        with:
          retries: 2
          retry-exempt-status-codes: 418
          script: |
            github.rest.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: '${{ github.event.number }}',
              name: 'props-bot'
            });
