##
# Automatically attempts to rerun a workflow.
##
name: Rerun Workflow

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'GitHub Action run ID to rerun'
        required: true
        type: 'string'

jobs:
  # Reruns the current workflow.
  #
  # Performs the following steps:
  # - Retrieves the current workflow run.
  # - Restarts all failed jobs when a workflow fails for the first time.
  rerun-workflow:
    name: Rerun Workflow
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Fetch the current workflow
        uses: desrosj/github-script@update/plugin-rest-endpoint-methods # v6.1.1
        with:
          script: |
            const workflow_run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ inputs.run_id }},
            });

            // Only automatically rerun after the first run attempt.
            if ( workflow_run.data.run_attempt > 1 ) {
              return;
            }

            const rerun = await github.rest.actions.reRunWorkflowFailedJobs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ inputs.run_id }},
            });
