##
# Automatically attempts to rerun a workflow.
##
name: Rerun Workflow

on:
  workflow_call:

jobs:
  # Reruns the current workflow.
  #
  # Performs the following steps:
  # - Retrieves the current workflow run.
  # - Restarts all failed jobs when a workflow fails for the first time.
  rerun-workflow:
    name: Prepare notifications
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Fetch the current workflow
        uses: actions/github-script@7a5c598405937d486b0331594b5da2b14db670da # v6.1.0
        with:
          script: |
            const workflow_run = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });

            // Only automatically retry after the first run attempt.
            if ( workflow_run.data.run_attempt > 1 ) {
              return;
            }

            const retry = await rest.actions.reRunWorkflowFailedJobs({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }},
            });
