##
# A reusable workflow that checks for uncommitted changes to built files in pull requests.
##
name: Check Built Files (PRs)

on:
  workflow_call:

permissions: {}

jobs:
  # Checks a PR for uncommitted changes to built files.
  #
  # When changes are detected, the patch is stored as an artifact for processing by the Commit Built File Changes
  # workflow.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Configures caching for Composer.
  # - Installs Composer dependencies.
  # - Logs general debug information about the runner.
  # - Installs npm dependencies.
  # - Builds CSS file using SASS.
  # - Builds Emoji files.
  # - Builds bundled Root Certificate files.
  # - Builds WordPress.
  # - Checks for changes to versioned files.
  # - Displays the result of git diff for debugging purposes.
  # - Saves the diff to a patch file.
  # - Uploads the patch file as an artifact.
  update-built-files:
    name: Check and update built files
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      # This date is used to ensure that the PHPCS cache is cleared at least once every week.
      # http://man7.org/linux/man-pages/man1/date.1.html
      - name: "Get last Monday's date"
        id: get-date
        run: echo "date=$(/bin/date -u --date='last Mon' "+%F")" >> "$GITHUB_OUTPUT"

      # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
      # passing a custom cache suffix ensures that the cache is flushed at least once per week.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          custom-cache-suffix: ${{ steps.get-date.outputs.date }}

      - name: Log debug information
        run: |
          npm --version
          node --version
          curl --version
          git --version

      - name: Install npm Dependencies
        run: npm ci

      - name: Run SASS precommit tasks
        run: npm run grunt precommit:css

      - name: Run Emoji precommit task
        run: npm run grunt precommit:emoji
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run certificate tasks
        run: npm run grunt copy:certificates

      - name: Build WordPress
        run: npm run build:dev

      - name: Check for changes to versioned files
        id: built-file-check
        run: |
          if git diff --quiet; then
            echo "uncommitted_changes=false" >> "$GITHUB_OUTPUT"
          else
            echo "uncommitted_changes=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Display changes to versioned files
        if: ${{ steps.built-file-check.outputs.uncommitted_changes == 'true' }}
        run: git diff

      - name: Save diff to a file
        if: ${{ steps.built-file-check.outputs.uncommitted_changes == 'true' }}
        run: git diff > ./changes.diff

      # Uploads the diff file as an artifact.
      - name: Upload diff file as artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ steps.built-file-check.outputs.uncommitted_changes == 'true' }}
        with:
          name: pr-built-file-changes
          path: changes.diff

  # Compares the results of npm run build with WordPress/WordPress
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up Node.js.
  # - Logs debug information about the GitHub Action runner.
  # - Installs npm dependencies.
  # - Builds WordPress to run from the build directory.
  # - Ensures version-controlled files are not modified or deleted.
  # - Checks out the WordPress/WordPress repository.
  # - Creates a directory for text files to be uploaded as an artifact.
  # - Storse a list of files that differ in the build directory from WordPress/WordPress.
  # - Storse a diff file comparing the build directory to WordPress/WordPress.
  # - Saves the pull request number to a text file.
  # - Uploads the generated files as an artifact.
  compare-built-files:
    name: Detect differences between WordPress/WordPress
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Set up PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2.37.0
        with:
          php-version: '8.4'
          coverage: none

      # Since Composer dependencies are installed using `composer update` and no lock file is in version control,
      # passing a custom cache suffix ensures that the cache is flushed at least once per week.
      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          custom-cache-suffix: $(/bin/date -u --date='last Mon' "+%F")

      - name: Log debug information
        run: |
          npm --version
          node --version
          git --version

      - name: Install npm Dependencies
        run: npm ci

      - name: Build WordPress to run from build directory
        run: npm run build

      - name: Ensure version-controlled files are not modified or deleted
        run: git diff --exit-code

      - name: Checkout WordPress/WordPress
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: 'WordPress/WordPress'
          path: ${{ github.workspace }}/built-wordpress
          show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
          persist-credentials: false

      - name: Create directory for artifacts
        run: mkdir artifacts

      - name: Create a list of files that have changed
        run: diff -rq ${{ github.workspace }}/build ${{ github.workspace }}/built-wordpress | sed "s|${{ github.workspace }}/||g" > artifacts/file-changes.txt

      - name: Create a list of files that have changed
        run: diff -r ${{ github.workspace }}/build ${{ github.workspace }}/built-wordpress | sed "s|${{ github.workspace }}/||g" > artifacts/changes.diff

      - name: Save PR number
        run: echo "${EVENT_NUMBER}" > ./artifacts/NR
        env:
          EVENT_NUMBER: ${{ github.event.number }}

      # Uploads the associated text files as an artifact.
      - name: Upload comparison results as an artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        #if: ${{ github.repository == 'WordPress/wordpress-develop' && github.event_name == 'pull_request' }}
        with:
          name: build-script-comparison
          path: artifacts/
