name: Test old branches

on:
  pull_request:
  pull_request_target:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

jobs:
  dispatch-workflows:
    name:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GHA_OLD_BRANCH_DISPATCH }}
    strategy:
      fail-fast: false
      matrix:
        workflow: [
          'coding-standards.yml',
          'end-to-end-tests.yml',
          'javascript-tests.yml',
          'php-compatibility.yml',
          'phpunit-tests.yml',
          'verify-npm-on-windows.yml'
        ]
        branch: [
           '5.7', '5.6', '5.5-test', '5.4', '5.3', '5.2', '5.1', '5.0',
           '4.9', '4.8', '4.7', '4.6', '4.5', '4.4', '4.3', '4.2', '4.1', '4.0',
           '3.9', '3.8', '3.7'
        ]
#        branch: [ '5.5-test' ]
    steps:
      - name: Dispatch workflow run (manually with cURL)
        run: |
          curl -u ":$TOKEN" \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/desrosj/wordpress-develop/actions/workflows/${{ matrix.workflow }}/dispatches \
          -d '{ "ref": "${{ matrix.branch }}" }'
