name: Test old branches

on:
  pull_request:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

jobs:
  dispatch-workflows:
    name: ${{ matrix.branch }} - ${{ matrix.workflow }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workflow: [
          'coding-standards.yml',
          'end-to-end-tests.yml',
          'javascript-tests.yml',
          'php-compatibility.yml',
          'phpunit-tests.yml',
          'verify-npm-on-windows.yml'
        ]
#        branch: [
#           '5.7', '5.6', '5.5-test', '5.4', '5.3', '5.2', '5.1', '5.0',
#           '4.9', '4.8', '4.7', '4.6', '4.5', '4.4', '4.3', '4.2', '4.1', '4.0',
#           '3.9', '3.8', '3.7'
#        ]
        branch: [ '5.5-test' ]
    steps:
      - name: Dispatch workflow run
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GHA_OLD_BRANCH_DISPATCH }}
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: '${{ matrix.workflow }}',
              ref: 'refs/heads/${{ matrix.branch }}'
            });
