name: test-exclude-array.yml
on:

jobs:
  # Tests the full list of PHP/MySQL combinations for the two most recent versions of WordPress.
  #
  # Only runs when testing the currently supported branch or latest/nightly.
  upgrade-tests-recent-releases:
    name: ${{ matrix.wp }} to latest
    uses: ./.github/workflows/reusable-upgrade-testing.yml
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-24.04' ]
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
        db-type: [ 'mysql' ]
        db-version: [ '5.7', '8.0', '8.4', '9.6' ]
        wp: [ '4.7', '5.0', '6.7', '6.8' ]
        multisite: [ false, true ]

        exclude:
          - php: [ '8.0', '8.1', '8.2', '8.3', '8.4', '8.5' ]
            wp: '4.7'

    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      wp: ${{ matrix.wp }}
      new-version: ${{ inputs.new-version && inputs.new-version || 'latest' }}
      multisite: ${{ matrix.multisite }}
